datasource:
  default: ${APP_ENV}
  dev:
    username: "sa"
    password: "sa"
    url: "jdbc:h2:./db"
  prod:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

ebean:
  dev:
    migration:
      run: true
  prod:
    migration:
      run: true