datasource:
  default: ${APP_ENV}
  dev:
    username: "sa"
    password: "sa"
    url: "jdbc:h2:./db"
  prod:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}

ebean:
  dev:
    migration:
      run: true
  prod:
    migration:
      run: true